<?php

namespace App\Http\Controllers\Portal;

use App\Http\Controllers\PortalController;
use App\Model\AppsOnline\AkunModel;
use App\Model\AppsOnline\JadwalModel;
use App\Model\BuatJanjiModel;
use App\Model\SimPel\DokterModel;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class HomeController extends PortalController {
    public function __construct(){
        $this->module = "home";
    }

    function index(Request $request){
        $this->data = (object)[
            "TotalMember"=>AkunModel::where("apps",1)->count(),
            "TotalPendaftarRajal" => 0,
        ];
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    function JadwalDokter(Request $request){
        $validator = Validator::make(
            $request->all(), [
            'tanggal'=>'required'
        ], [
                'tanggal.required' => 'tanggal harus diisi',
            ]
        );

        if ($validator->fails()){
            return response()->json([
                "diagnostic" => $this->diagnostic(
                    microtime(true),
                    $validator->messages()->first(),
                    422
                )
            ]);
        }
        $day = date('w', strtotime($request->tanggal));
        $data = JadwalModel::where("hari",$day)
            ->where("fl_status",1)->orderBy("jam_buka")->get();
        foreach ($data as $key => $row){
            $data[$key]["DOKTER"] = DokterModel::getDetail(["id"=>$row->id_dokter,"smf" => $request->smf]);
            $data[$key]["PENDAFTAR"] = BuatJanjiModel::where("tanggaljanjian",$request->tanggal)
                ->where("id_jadwal",$row->id)->get();
        }
        $content = view('portal.'.$this->module.'.jadwal',compact('data'))->render();
        return response()->json([
            "status" => 200,
            "content" => $content
        ]);
    }
}
